title: "Pouya Ahadi"
description: "Ph.D. candidate in Machine Learning at Georgia Tech"
theme: jekyll-theme-minimal
logo: /assets/img/Pouya_Ahadi_profile.jpg
show_downloads: false

# Social links
linkedin_username: pouya-ahadi-06947712b
google_scholar: true
email: pouya.ahadi@gatech.edu
